create table if not exists public.easton_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event text not null check (event in ('visit','cta_click','lead_submit')),
  route text not null,
  path text,
  client_ts timestamptz,
  address text,
  bin_count text,
  contact text,
  price_acceptance text check (price_acceptance is null or price_acceptance in ('yes','maybe','no'))
);
alter table public.easton_events enable row level security;
-- No public insert/select policies: writes happen only through the server-side collector.
create index if not exists easton_events_route_event_idx on public.easton_events(route,event);
